<a href="https://colab.research.google.com/github/DavidSenseman/STA1403/blob/main/Chapter_07B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- STA1403_CHAPTER_07B:Rev 1 -->

---------------------------
**COPYRIGHT NOTICE:** This Jupyterlab Notebook is a Derivative work of [Jeff Heaton](https://github.com/jeffheaton) licensed under the Apache License, Version 2.0 (the "License"); You may not use this file except in compliance with the License. You may obtain a copy of the License at

> [http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0)

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

------------------------

# **STA 1403: Biostatistics**

### **Chapter 7: Hypothesis Testing**

* Instructor: [David Senseman](mailto:David.Senseman@utsa.edu), [Department of Biology, Health and the Environment](https://sciences.utsa.edu/bhe/), [UT San Antonio](https://www.utsa.edu/)

#### Contents
* 7.1 : Introduction
* 7.2 : Hypothesis Testing for the Population Mean
* 7.3 : Statistical Significance
* **7.4 : Hypothesis Testing Using $t$-tests**
* **7.5 : Hypothesis Testing for the Population Proportion**
* **7.6 : Advanced**

## Google Colab Instructions

Run next code cell to map this Colab lesson's folder /content/drive to your Google Drive. This will allow you keep a copy of this Colab notebook which **_is_** your course textbook.

In [ ]:
# @title **Run this cell first**
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    Colab = True
    print("Note: Using Google CoLab")
    !curl ipinfo.io
except:
    print("**WARNING**: Your GDrive is not mapped to /content/drive ")
    print("**WARNING**: Your work will not be saved!")
    Colab = False

Mounted at /content/drive
Note: Using Google CoLab
{
  "ip": "34.106.206.81",
  "hostname": "81.206.106.34.bc.googleusercontent.com",
  "city": "Salt Lake City",
  "region": "Utah",
  "country": "US",
  "loc": "40.7608,-111.8911",
  "org": "AS396982 Google LLC",
  "postal": "84101",
  "timezone": "America/Denver",
  "readme": "https://ipinfo.io/missingauth"
}

You should see something _similar_ to the following output:
```text
Mounted at /content/drive
Note: Using Google CoLab
{
  "ip": "34.139.115.187",
  "hostname": "187.115.139.34.bc.googleusercontent.com",
  "city": "North Charleston",
  "region": "South Carolina",
  "country": "US",
  "loc": "32.8546,-79.9748",
  "org": "AS396982 Google LLC",
  "postal": "29415",
  "timezone": "America/New_York",
  "readme": "https://ipinfo.io/missingauth"
}
```

## Test Your STA1403 Key

Run the next cell to test whether your STA1403 Key is correctly installed in your Colab Secrets.

In [ ]:
# @title Test Your STA1403 Key

from google.colab import userdata
import os

# Check if API key is properly loaded
try:
    # 1. Get the key from Secrets
    STA1403_KEY = userdata.get('STA1403_KEY')

    # 2. Set it as an environment variable
    os.environ['STA1403_KEY'] = STA1403_KEY

    print("STA1403 key loaded and environment variable set successfully!")
    print(f"Key length: {len(STA1403_KEY)}")

except Exception as e:
    print(f"Error loading STA1403 Key: {e}")
    print("Please set your STA1403 key in Google Colab:")
    print("1. Go to Secrets in the left sidebar (key icon)")
    print("2. Create a new secret named 'STA1403_KEY'")
    print("3. Paste your STA1403 key and toggle 'Notebook access' on")

STA1403 key loaded and environment variable set successfully!
Key length: 26


If your STA1403 Key is correctly stored in your Colab Secrets, you should see the following output:
```text
STA1403 key loaded and environment variable set successfully!
Key length: 28
```
Contact your Instructor if you recieve an error since you won't be able to submit your lesson for grading unless your STA1403 key is correctly installed.

## Load Datasets

Run the next cell to load the datasets for this lesson.

In [ ]:
# @title Load Datasets
import pandas as pd

# Load birthwt dataset
Pima_df = pd.read_csv("https://biologicslab.co/STA1403/data/Pima.tr",
                      sep=',', na_values=[" ", "NA", "null", ""])
# Replace any na with median
Pima_df['bmi'] = Pima_df['bmi'].fillna(Pima_df['bmi'].median())
#Pima_df.head()

# Load BodyTemperature.txt dataset
bodyTemp_df = pd.read_csv("https://biologicslab.co/STA1403/data/BodyTemperature.txt",
                         sep=' ', na_values=[" ", "NA", "null", ""])
#bodyTemp_df.head()

# Load Melanoma.txt dataset
melanoma_df = pd.read_csv("https://biologicslab.co/STA1403/data/melanoma.csv")
# melanoma_df.head()


print("Datasets loaded sucessfully. ✅")

Datasets loaded sucessfully. ✅


# **Chapter 7 - Hypothesis Testing**

## **7.4 Hypothesis Testing Using _t_-tests**

So far, we have assumed that the population variance $\sigma^{2}$ is known. Therefore, evaluating a hypothesis regarding the population mean did not involve estimating $\sigma^{2}$. In reality, $\sigma^{2}$ is almost always unknown, and we need to estimate it from the data. As before, we estimate $\sigma^{2}$ using the sample variance $S^{2}$. We would be of course uncertain about our estimate of $\sigma^{2}$, and our hypothesis testing procedure should take this additional source of uncertainty into account. Similar to our approach for finding confidence intervals, we account for this additional source of uncertainty by using the $t$-distribution with $n-1$ degrees of freedom instead of the standard normal distribution. The hypothesis testing procedure is then called the **$t$-test**.

To perform a $t$-test, we use the following test statistic (instead of $Z$):
$$
T = \frac {\bar {X} - \mu_{0}}{S / \sqrt {n}},
$$

where $\bar{X}$ is the sample mean, $n$ is the sample size, $S$ is the sample standard deviation, and $\mu_{0}$ is the null value. The test statistic, $T$, has a $t$-distribution with $n-1$ degrees of freedom under the null.

$$
T \sim t(n - 1).
$$

Using the observed values of $\bar{X}$ and $S$, the observed value of the test statistic is obtained as follows:

$$
t = \frac {\bar {x} - \mu_ {0}}{s / \sqrt {n}}.
$$

We refer to $t$ as the **$t$-score**.

Suppose we hypothesize that the population mean of BMI among Pima Indian women is above 30: $H_{A}: \mu > 30$. The corresponding null hypothesis is $H_{0}: \mu = 30$. To test this hypothesis, we use the Pima.tr data set.

The sample size is $n = 200$. The sample mean and standard deviation are $\bar{x} = 32.31$ and $s = 6.13$, respectively. The $t$-score is
$$
t = \frac {32.31 - 30}{6.13 / \sqrt {200}} = 5.33.
$$

-----------------------------------

>To assess the null hypothesis $H_{0}: \mu = \mu_{0}$ using the $t$-test, we first calculate the $t$-score based on the observed sample mean $\bar{x}$ and sample standard deviation. We then calculate the corresponding $p$-value as follows:
$$
\begin{array}{l}
\text {if } H_{A}:\mu < \mu_ {0},\quad p_{\mathrm {o b s}} = P(T \leq t), \\
\text {if } H_ {A}: \mu > \mu_{0}, \quad p_{\mathrm {obs}} = P(T \geq t), \\
\text {if } H_{A}:\mu \neq \mu_{0}, \quad p_{\mathrm {obs}} = 2 \times P(T \geq | t |), \\
\end{array}
$$
where $T$ has a $t$-distribution with $n-1$ degrees of freedom, and $t$ is our observed $t$-score. This is known as the **single-sample** $t$-**test**.

--------------------------------

For the above example, $p_{\mathrm{obs}} = P(T \geq 5.33)$, which we obtain from the $t$-distribution with $200 - 1 = 199$ degrees of freedom.

The resulting probability is $1.33 \times 10^{-07}$, which is shown as 1.33e-07. This is quite small and leads us to conclude that the result is statistically significant. At any reasonable significance level, there is strong evidence to reject the null hypothesis and conclude that the population mean of BMI among Pima Indian women is in fact greater than $30$. Therefore, on average, the population is obese.

We can use Python to perform a $t$-test directly. For example, let us consider the `Pima.tr` data set and test the hypothesis that $H_{0}:\mu=30$ against $H_{A}:\mu>30$ for the BMI of Pima Indian women as shown in Example 1.

## Example 1: Perform $t$-Test

In [ ]:
# @title Example 1: Perform t-Test

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# Set parameters
data_samples=Pima_df["bmi"]
mu_0 = 30  # mean H0

# Set seed
np.random.seed(42)

# Compute sample statistics
n_obs = len(data_samples)
x_bar = np.mean(data_samples)
s = np.std(data_samples, ddof=1)  # sample standard deviation
std_error = s / np.sqrt(n_obs)

# Compute t-statistic manually
t_calc = (x_bar - mu_0) / std_error

# One-sample t-test (two-tailed by default in scipy)
t_result = stats.ttest_1samp(data_samples, mu_0)

# scipy gives two-tailed p-value; divide by 2 for one-tailed (upper)
p_value_test = t_result.pvalue / 2 if t_result.statistic > 0 else 1 - t_result.pvalue / 2

print()
print("=== One-sample t-test on data ===")
print(f"Sample size:    {n_obs}")
print(f"Sample mean:    {x_bar:.3f}")
print(f"Sample std dev: {s:.3f}")
print(f"Standard error: {std_error:.4f}")
print(f"t-score:        {t_calc:.2f}")
print(f"Degrees of free: {n_obs - 1}")
print(f"p-value (one-tail): {p_value_test:.4f}")

# Decision at common significance levels
alpha_levels = [0.01, 0.05, 0.10]
print()
print("=== Hypothesis test decisions ===")
for alpha in alpha_levels:
    decision = "REJECT H0" if p_value_test < alpha else "Fail to reject H0"
    print(f"At alpha = {alpha}: {decision} (p = {p_value_test:.4f})")




=== One-sample t-test on data ===
Sample size:    200
Sample mean:    32.322
Sample std dev: 6.129
Standard error: 0.4334
t-score:        5.36
Degrees of free: 199
p-value (one-tail): 0.0000

=== Hypothesis test decisions ===
At alpha = 0.01: REJECT H0 (p = 0.0000)
At alpha = 0.05: REJECT H0 (p = 0.0000)
At alpha = 0.1: REJECT H0 (p = 0.0000)


If the code is correct, you should see the following output:
```text

=== One-sample t-test on data ===
Sample size:    200
Sample mean:    32.322
Sample std dev: 6.129
Standard error: 0.4334
t-score:        5.36
Degrees of free: 199
p-value (one-tail): 0.0000

=== Hypothesis test decisions ===
At alpha = 0.01: REJECT H0 (p = 0.0000)
At alpha = 0.05: REJECT H0 (p = 0.0000)
At alpha = 0.1: REJECT H0 (p = 0.0000)
```

For the above example, $p_{\mathrm{obs}} = P(T \geq 5.33)$, which we obtain from the $t$-distribution with $200 - 1 = 199$ degrees of freedom. The resulting $p$-value is $1.33 \times 10^{-07}$, which is shown above as $0.0000$. This is quite small and leads us to conclude that the result is statistically significant. At any reasonable significance level, there is strong evidence to reject the null hypothesis and conclude that the population mean of `BMI` among Pima Indian women is in fact greater than $30$. Therefore, on average, the population is obese.

## **Exercise 1: Perform t-Test**

In the cell below, write the code to perform a $t$-Test on the variable body temperature (`Temperature`) from the BodyTemperature dataset. This data has been previously stored in the `bodyTemp_df` DataFrame.

**Code Hints:**

Set the paramters as follows:
```text
# Set parameters
data_samples=bodyTemp_df["Temperature"]
mu_0 = 98.6  # mean H0
```


In [ ]:
# @title Exercise 1: Perform t-Test

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# Set parameters
data_samples=bodyTemp_df["Temperature"]
mu_0 = 98.6  # mean H0

# Set seed
np.random.seed(42)

# Compute sample statistics
n_obs = len(data_samples)
x_bar = np.mean(data_samples)
s = np.std(data_samples, ddof=1)  # sample standard deviation
std_error = s / np.sqrt(n_obs)

# Compute t-statistic manually
t_calc = (x_bar - mu_0) / std_error

# One-sample t-test (two-tailed by default in scipy)
t_result = stats.ttest_1samp(data_samples, mu_0)

# scipy gives two-tailed p-value; divide by 2 for one-tailed (upper)
p_value_test = t_result.pvalue / 2 if t_result.statistic > 0 else 1 - t_result.pvalue / 2

print()
print("=== One-sample t-test on data ===")
print(f"Sample size:    {n_obs}")
print(f"Sample mean:    {x_bar:.3f}")
print(f"Sample std dev: {s:.3f}")
print(f"Standard error: {std_error:.4f}")
print(f"t-score:        {t_calc:.2f}")
print(f"Degrees of free: {n_obs - 1}")
print(f"p-value (one-tail): {p_value_test:.4f}")

# Decision at common significance levels
alpha_levels = [0.01, 0.05, 0.10]
print()
print("=== Hypothesis test decisions ===")
for alpha in alpha_levels:
    decision = "REJECT H0" if p_value_test < alpha else "Fail to reject H0"
    print(f"At alpha = {alpha}: {decision} (p = {p_value_test:.4f})")




=== One-sample t-test on data ===
Sample size:    100
Sample mean:    98.330
Sample std dev: 0.957
Standard error: 0.0957
t-score:        -2.82
Degrees of free: 99
p-value (one-tail): 0.9971

=== Hypothesis test decisions ===
At alpha = 0.01: Fail to reject H0 (p = 0.9971)
At alpha = 0.05: Fail to reject H0 (p = 0.9971)
At alpha = 0.1: Fail to reject H0 (p = 0.9971)


If the code is correct, you should see the following output:
```text
=== One-sample t-test on data ===
Sample size:    100
Sample mean:    98.330
Sample std dev: 0.957
Standard error: 0.0957
t-score:        -2.82
Degrees of free: 99
p-value (one-tail): 0.9971

=== Hypothesis test decisions ===
At alpha = 0.01: Fail to reject H0 (p = 0.9971)
At alpha = 0.05: Fail to reject H0 (p = 0.9971)
At alpha = 0.1: Fail to reject H0 (p = 0.9971)
```

Since the $p$-value of $0.9971$ is much larger than the cutoff value of $0.05$, we fail to reject the null hypothesis $H_{0}$. In other words, the difference between our sample mean, $98.33^\circ$F, and the accepted value of $98.6^\circ$F, can be simply explained by sampling error.   

## **7.5 Hypothesis Testing for Population Proportion**

For a binary random variable $X$ with possible values $0$ and $1$, we are typically interested in evaluating hypotheses regarding the population proportion of the outcome of interest, denoted as $X=1$. As discussed before, the population proportion is the same as the population mean for such binary variables. So we follow the same procedure as described above. More specifically, we use the $z$-test for hypothesis testing. Note that we do not use $t$-test, because for binary random variable, population variance is $\sigma^{2}=\mu(1-\mu)$. Therefore, by setting $\mu=\mu_{0}$ according to the null hypothesis, we also specify the population variance as $\sigma^{2}=\mu_{0}(1-\mu_{0})$ so we do not need to estimate the population variance separately.

Now, if we assume that the null hypothesis is true, we have

$$
\bar {X} | H_{0} \sim N \left(\mu_{0}, \mu_{0} \left(1 - \mu_{0}\right)\right).
$$

This means that

$$
Z = \frac {\bar {X} - \mu_{0}}{\sqrt {\mu_{0} \left(1 - \mu_{0}\right) / n}} \sim N(0, 1).
$$

As a result, we obtain the $z$-score as follows:

$$
z = \frac {p - \mu_{0}}{\sqrt {\mu_{0} \left(1 - \mu_{0}\right) / n}},
$$

where $p$ is the sample proportion (mean).

Consider the `Melanoma` example. Suppose that we hypothesize that less than 50% of cases ulcerate: $\mu < 0.5$. Then the null hypothesis can be expressed as $H_{0}: \mu = 0.5$. Using the Melanoma data set, Example 2 shows how we can test the above null hypothesis.

--------------------------------


>In general, to assess the null hypothesis $H_{0}:\mu=\mu_{0}$, where $\mu$ is the population proportion (mean) of a binary random variable, we first calculate $z$-score based on the observed sample proportion $p$:
$$
z = \frac {p - \mu_ {0}}{\sqrt {\mu_ {0} \left(1 - \mu_ {0}\right) / n}}.
$$
Then we determine the support for the null hypothesis as:
$$
\begin{array}{l}
\text {if } H_{A}: \mu < \mu_{0}, \quad p_{\mathrm {obs}} = P(Z \leq z), \\
\text {if } H_{A}: \mu > \mu_{0}, \quad p_{\mathrm {obs}} = P (Z \geq z), \\
\text {if } H_{A}: \mu \neq \mu_{0}, \quad p_{\mathrm {o b s}} = 2 \times P (Z \geq | z |), \\
\end{array}
$$
where $Z$ has the standard normal distribution, and $z$ is the observed $z$-score.

--------------------

## Example 2: Hypothesis Testing for Population Proportion

The Python code in the next cell uses the `melanoma` dataset to find the $z$-score for our test statistic as follows:
$$
z = \frac {0.44 - 0.5}{\sqrt {0.5 (1 - 0.5) / 205}} = - 1.75.
$$  

In [ ]:
# @title Example 2: Hypothesis Testing for Population Proportion

import numpy as np
from scipy.stats import norm

# Set alpha
alpha = 0.05

# Set parameters
data_samples=melanoma_df["ulcer"]
p_null = 0.5  # null hypothesis proportion

# Set seed
np.random.seed(42)

# Compute sample statistics
n_ulcers = sum(data_samples)
n = len(data_samples)
p_observed = round(n_ulcers / n, 2)     # observed proportion

# Calculate z-score
z_score = (p_observed - p_null) / np.sqrt(p_null * (1 - p_null) / n)

# Calculate p-value (lower tail probability)
p_value = norm.cdf(z_score)

# Interpret results
if p_value < alpha:
    decision1 = "Reject H₀"
    decision2 = "< than alpha."
else:
    decision1 = "Fail to reject"
    decision2 = "> than alpha."

# Print results
print("--------Hypothesis Testing for Population Proportion---------------------")
print(f"Number of observations: {n}")
print(f"Number of ulceration cases: {n_ulcers}")
print(f"Observed proportion: {p_observed:.4f}")
print(f"Null hypothesis proportion: {p_null}")
print(f"Z-score: {z_score:.2f}")
print(f"P-value: {p_value:.3f}")
print(f"\nDecision:")
print(f"{decision1}: At alpha = {alpha}, the p-value = {p_value:3f} {decision2} ")
print("-" * 73)


--------Hypothesis Testing for Population Proportion---------------------
Number of observations: 205
Number of ulceration cases: 91
Observed proportion: 0.4400
Null hypothesis proportion: 0.5
Z-score: -1.72
P-value: 0.043

Decision:
Reject H₀: At alpha = 0.05, the p-value = 0.042886 < than alpha. 
-------------------------------------------------------------------------


If the code is correct, you should see the following output:
```text
--------Hypothesis Testing for Population Proportion---------------------
Number of observations: 205
Number of ulceration cases: 91
Observed proportion: 0.4400
Null hypothesis proportion: 0.5
Z-score: -1.72
P-value: 0.043

Decision:
Reject H₀: At alpha = 0.05, the p-value = 0.042886 < than alpha.
-------------------------------------------------------------------------
```

Because $H_{A}:\mu<0.5$, the observed significance level based on this $z$-score is the lower tail probability $P(Z\leq-1.72)$. Using Python, we find the $p$-value to be $p_{obs}=0.043$. Therefore, we can reject the null hypothesis at $0.05$ level

## **Exercise 2: Hypothesis Testing for Population Proportion**

Repeat the analysis performed in Example 1, but change the value of alpha to `0.01`.

In [ ]:
# @title Example 2: Hypothesis Testing for Population Proportion

import numpy as np
from scipy.stats import norm

# Set alpha
alpha = 0.01

# Set parameters
data_samples=melanoma_df["ulcer"]
p_null = 0.5  # null hypothesis proportion

# Set seed
np.random.seed(42)

# Compute sample statistics
n_ulcers = sum(data_samples)
n = len(data_samples)
p_observed = round(n_ulcers / n, 2)     # observed proportion

# Calculate z-score
z_score = (p_observed - p_null) / np.sqrt(p_null * (1 - p_null) / n)

# Calculate p-value (lower tail probability)
p_value = norm.cdf(z_score)

# Interpret results
if p_value < alpha:
    decision1 = "Reject H₀"
    decision2 = "< than alpha."
else:
    decision1 = "Fail to reject"
    decision2 = "> than alpha."

# Print results
print("--------Hypothesis Testing for Population Proportion---------------------")
print(f"Number of observations: {n}")
print(f"Number of ulceration cases: {n_ulcers}")
print(f"Observed proportion: {p_observed:.4f}")
print(f"Null hypothesis proportion: {p_null}")
print(f"Z-score: {z_score:.2f}")
print(f"P-value: {p_value:.3f}")
print(f"\nDecision:")
print(f"{decision1}: At alpha = {alpha}, the p-value = {p_value:3f} {decision2} ")
print("-" * 73)


--------Hypothesis Testing for Population Proportion---------------------
Number of observations: 205
Number of ulceration cases: 91
Observed proportion: 0.4400
Null hypothesis proportion: 0.5
Z-score: -1.72
P-value: 0.043

Decision:
Fail to reject: At alpha = 0.01, the p-value = 0.042886 > than alpha. 
-------------------------------------------------------------------------


If the code is correct, you should see the following output:
```text
--------Hypothesis Testing for Population Proportion---------------------
Number of observations: 205
Number of ulceration cases: 91
Observed proportion: 0.4400
Null hypothesis proportion: 0.5
Z-score: -1.72
P-value: 0.043

Decision:
Fail to reject: At alpha = 0.01, the p-value = 0.042886 > than alpha.
-------------------------------------------------------------------------
```

Because $H_{A}:\mu>0.5$, the observed significance level based on this $z$-score is the lower tail probability $P(Z\leq-1.75)$. As in Example 2, we find the $p$-value to be $p_{obs}=0.0439$. However, this time we fail to reject the null hypothesis at $0.01$ level

## **7.6 Advanced**

In statistics, it is often convenient to assume normal distributions for random variables. In this section, we discuss a formal test of normality. We also discuss some useful Python functions for hypothesis testing.

### **_7.6.1 Test of Normality_**

Previously, we used Q–Q plots to visually assess the appropriateness of normality assumption for random variables. The appropriateness of the normality assumption can be evaluated formally using a testing procedure such as the Shapiro–Wilk test of normality. More specifically, this test evaluates the null hypothesis that the distribution of the random variable is normal. As usual, we then either reject this hypothesis and conclude that the normality assumption is not appropriate, or fail to reject it and conclude that there is no strong evidence of deviation from normality.

Suppose we assume that the `bmi` variable in `Pima.tr` has normal distribution. The code in Example 3 shows how we can evaluate this assumption using Python.

## Example 3: Test Normality

The code in the cell below, uses a statistical test called the **Shapiro-Wilk test** to see if the `bmi` variable in the `Pima.tr` dataset has a normal distribution.

In [ ]:
# @title Example 3: Test Normality

import scipy.stats as stats

# Configuration
df = Pima_df
column_name = ['bmi']

# Set cutoff
alpha = 0.05

# --------Execute test------------------------------

# Clean data for testing (remove NaNs)
data = df[column_name].dropna()

# Perform Shapiro-Wilk test
print(f"--------Performing Shapiro-Wilk's test on {column_name} ------------------------")
stat, p_value = stats.shapiro(data)

# Interpret results
if p_value < alpha:
    decision = "Reject null hypothesis. Deviation from normality is significant."
else:
    decision = "Fail to reject null hypothesis. No strong evidence of deviation from normality."

# Print result
print(f"Shapiro-Wilk p-value: {p_value:.4f}")
print(f"Result: {decision}")
print("-" * 74)


--------Performing Shapiro-Wilk's test on ['bmi'] ------------------------
Shapiro-Wilk p-value: 0.2292
Result: Fail to reject null hypothesis. No strong evidence of deviation from normality.
--------------------------------------------------------------------------


If the code is correct, you should see the following output:

```text
--------Performing Shapiro-Wilk's test on ['bmi'] ------------------------
Shapiro-Wilk p-value: 0.2292
Result: Fail to reject null hypothesis. No strong evidence of deviation from normality.
--------------------------------------------------------------------------
```

The $p$-value for this test is $0.23$. Therefore, we do _not_ reject the null hypothesis (which states that the distribution is normal) and conclude that the deviation of the distribution from normality is not statistically significant.

For comparison, repeat the above steps to test the normality assumption for the age variable in the `Pima.tr` data set.

## **Exercise 3: Test Normality**

In the cell below, write the code to test the normality of the variable `age` in the `Pima.tr` dataset.

In [ ]:
# @title Exercise 3: Test Normality

import scipy.stats as stats

# Configuration
df = Pima_df
column_name = ['age']

# Set cutoff
alpha = 0.05

# --------Execute test------------------------------

# Clean data for testing (remove NaNs)
data = df[column_name].dropna()

# Perform Shapiro-Wilk test
print(f"--------Performing Shapiro-Wilk's test on {column_name} ------------------------")
stat, p_value = stats.shapiro(data)

# Interpret results
if p_value < alpha:
    decision = "Reject null hypothesis. Deviation from normality is significant."
else:
    decision = "Fail to reject null hypothesis. No strong evidence of deviation from normality."

# Print result
print(f"Shapiro-Wilk p-value: {p_value:.4f}")
print(f"Result: {decision}")
print("-" * 74)

--------Performing Shapiro-Wilk's test on ['age'] ------------------------
Shapiro-Wilk p-value: 0.0000
Result: Reject null hypothesis. Deviation from normality is significant.
--------------------------------------------------------------------------


If the code is correct, you should see the following output:
```text
--------Performing Shapiro-Wilk's test on ['age'] ------------------------
Shapiro-Wilk p-value: 0.0000
Result: Reject null hypothesis. Deviation from normality is significant.
--------------------------------------------------------------------------
```

Using the Shapiro-Wilk test, the $p$-value is $1.853 \times 10^{-12}$, which is quite small. Therefore, we can comfortably reject the null hypothesis and conclude that for the variable `age`, the deviation from normality is statistically significant.

### **_7.6.2 Hypothesis Testing with Python Programming_**

To perform the $z$-test in Python, we can use the function `norm.cdf()` in order to find the $p$-value. For the body temperature example discussed at the beginning of this chapter, the $z$-score was $-1$. For the one-sided hypothesis of the form $H_{0}:\mu<\mu_{0}$, we find the lower tail probability of $-1$ as shown in **Exercise 4**.

In [ ]:
# @title Exercise 4
from scipy.stats import norm
result = norm.cdf(-1, loc=0, scale=1)
print(result)

0.15865525393145707


In the function `norm.cdf(x, loc, scale)` the argument `loc` is the mean, and the argument `scale` is the standard deviation. This function will output the cumulative probability up to the value of `x` (in this example $-1$) in a standard normal distribution. Importantly, the default behavior of this function is to output the _lower tail_ probability.

For the two-sided hypothesis, we multiply the above probability by $2$. Similar approach is used for testing one-sided or two-sided hypothesis regarding population proportion.  

For the BMI example, the $z$-score was $1.67$. For the one-sided hypothesis of the form $H_{0}:\mu>\mu_{0}$, we need to find the upper tail probability of $1.67$ as follows in **Exercise 5**.

In [ ]:
# @title Exercise 5
from scipy.stats import norm
result = 1 - norm.cdf(1.67, loc=0, scale=1)
print(result)

0.04745968180294735


In this example, `norm.cdf(1.67, loc=0, scale=1)` gives us $P(X \le 1.67)$ for a standard normal distribution. Since `norm.cdf()` generates the lower tail probability, we need to substact the result from $1$ to get the _upper_ tail probability.

When $\sigma^{2}$ is unknown and we need to use the data to estimate it separately, we use the $t$-test to evaluate hypotheses regarding the mean of a normal distribution. For the BMI example in Sect. 7.4, we found $t$-score was $t = 5.33$. For the one-sided hypothesis of the form $H_{0}:\mu>\mu_{0}$, we need to find the upper tail probability of $5.33$ from a $t$-distribution with $n - 1$ degrees of freedom, where $n = 200$ in this example. We use the `t.cdf()` function as shown in **Exercise 6**.

In [ ]:
# @title Exercise 6
from scipy.stats import t
result = 1 - t.cdf(5.33, df=199)
print(result)

1.3247781083247645e-07


Since the function `t.cdf()` returns the lower tail probability, we need to subtract this value from $1$ to get the _upper_ tail probability as was done in the previous example.

Alternatively, instead of calculating the $t$-score and finding the appropriate tail probabilities to obtain the $p$-value, we can use the function #t.test()#. For the BMI example, we use this function as follows in **Exercise 7**.

In [ ]:
# @title Exercise 7

from scipy.stats import ttest_1samp

t_stat, p_value = ttest_1samp(Pima_df['bmi'], 30)
print(f"t-statistic: {t_stat}")
print(f"p-value: {p_value}")

t-statistic: 5.357985648242077
p-value: 2.3148371565041477e-07


The function `ttest_1samp(data, population_mean)` performs a one-sample $t$-test on the data in the `BMI` column from the `Pima_df` pandas DataFrame). The function returns both the $t$-statistic and $p$-value. This tests whether the sample mean BMI is significantly different from $30$.   

# **Electronic Submission**

When you run the code in the cell below, it will grade your Colab notebook and tell you your pending grade as it currently stands. You will be given the choice to either submit your notebook for final grading or the option to continue your work on one (or more) Exercises.

Grant Access to your Colab Secrets if you are asked to do so.

In [ ]:
# @title Electronic Submission

import urllib.request
import ssl
import time

url = "https://biologicslab.co/STA1403/backend_code/validate.py?v=" + str(time.time())

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

req = urllib.request.Request(
    url,
    headers={
        "Cache-Control": "no-cache, no-store, must-revalidate",
        "Pragma": "no-cache",
        "Expires": "0"
    }
)

with urllib.request.urlopen(req, context=ctx) as r:
    exec(r.read().decode("utf-8"))

main()